import test from 'node:test';
import assert from 'node:assert/strict';
import {layout,createGame,createPlayer,start,perform,legalMoves,missileTargets,cell,safe} from '../game.mjs';
function game(n=5){const g=createGame('ABCDEF','Ada');g.players.push(createPlayer('Bo',1));g.settings.size=n;g.settings.timer=0;start(g);g.turn=0;return g}
function move(g,rocket,score){g.step='move';g.score=score;perform(g,g.players[g.turn].id,{type:'move',rocket})}
test('reference 5 path and both sizes are adjacent with all cells covered',()=>{assert.deepEqual(layout().path,[[4,2],[4,3],[4,4],[3,4],[2,4],[1,4],[0,4],[0,3],[0,2],[0,1],[0,0],[1,0],[2,0],[3,0],[4,0],[4,1],[3,1],[2,1],[1,1],[1,2],[1,3],[2,3],[3,3],[3,2],[2,2]]);for(const n of [5,7])for(const d of ['reference','mirror'])for(let seat=0;seat<4;seat++){const l=layout(n,d,seat);assert.equal(new Set(l.path.map(x=>x.join())).size,n*n);assert.deepEqual(l.path.at(-1),[n>>1,n>>1]);for(let i=1;i<l.path.length;i++)assert.equal(Math.abs(l.path[i][0]-l.path[i-1][0])+Math.abs(l.path[i][1]-l.path[i-1][1]),1)}});
test('server casts only legal shell values and bonus scores',()=>{for(const count of [0,1,2,3,4]){const g=game();let i=0;perform(g,g.players[0].id,{type:'cast'},()=>i++<count?1:0);assert.equal(g.score,count||8);assert.equal(g.bonus,count===0||count===4)}});
test('capture returns opponent, unlocks spiral, grants bonus',()=>{const g=game(),[a,b]=g.players;a.rockets[0]=0;b.rockets[0]=layout(5,'reference',1).path.findIndex(x=>x.join()==='4,3');move(g,0,1);assert.equal(b.rockets[0],0);assert.equal(a.captured,true);assert.equal(a.stats.captures,1);assert.equal(g.turn,0);assert.equal(a.missiles,1)});
test('safe squares cannot capture and may stack',()=>{const g=game(),[a,b]=g.players;b.rockets[0]=layout(5,'reference',1).path.findIndex(x=>x.join()==='4,4');move(g,0,2);assert.equal(a.captured,false);assert.deepEqual(cell(g,b,0),[4,4]);assert.ok(safe(g,cell(g,a,0)))});
test('capture gate loops outer ring and opens inner route',()=>{const g=game(),a=g.players[0];a.rockets[0]=14;move(g,0,2);assert.equal(a.rockets[0],0);g.turn=0;a.captured=true;a.rockets[0]=14;move(g,0,2);assert.equal(a.rockets[0],16)});
test('missile hit spends ammo, resets target, does not unlock or grant bonus',()=>{const g=game(),[a,b]=g.players;a.missiles=1;g.step='attack';b.rockets[0]=layout(5,'reference',1).path.findIndex(x=>x.join()==='4,3');assert.ok(missileTargets(g).some(x=>x.player===b.id&&x.rocket===0));perform(g,a.id,{type:'fire',player:b.id,rocket:0});assert.equal(a.missiles,0);assert.equal(a.captured,false);assert.equal(b.rockets[0],0);assert.equal(g.turn,1)});
test('missiles protect safe, inner, hangar and arrived rockets',()=>{const g=game(),[a,b]=g.players;a.missiles=2;g.step='attack';b.rockets=[0,17,-1,24];assert.deepEqual(missileTargets(g),[])});
test('all four required for victory and overshoot docks',()=>{const g=game(),a=g.players[0];a.captured=true;a.rockets=[24,24,22,0];move(g,2,8);assert.equal(g.phase,'playing');g.turn=0;a.rockets[3]=23;move(g,3,8);assert.equal(g.phase,'finished');assert.equal(g.winner,a.id);perform(g,a.id,{type:'rematch'});assert.equal(g.phase,'lobby')});
test('launch gate and own landing collision are enforced',()=>{const g=game(),a=g.players[0];a.rockets=[-1,-1,-1,-1];g.step='move';g.score=1;assert.deepEqual(legalMoves(g),[]);g.score=4;assert.equal(legalMoves(g).length,4);perform(g,a.id,{type:'move',rocket:0});assert.equal(a.rockets[0],0);g.turn=0;a.rockets=[0,1,0,0];g.step='move';g.score=1;assert.ok(!legalMoves(g).includes(0))});
test('boost, asteroid, wormhole and cache cap resolve once',()=>{for(const [from,score,to] of [[10,1,13],[2,1,1],[6,1,15]]){const g=game();g.players[0].rockets[0]=from;move(g,0,score);assert.equal(g.players[0].rockets[0],to)}const g=game();g.players[0].missiles=2;move(g,0,1);assert.equal(g.players[0].missiles,2)});
test('wrong turn and illegal action rejected',()=>{const g=game();assert.throws(()=>perform(g,g.players[1].id,{type:'cast'}),/turn/);assert.throws(()=>perform(g,g.players[0].id,{type:'fire',rocket:0}),/available/)});
test('complete simulated matches on 5 and 7, all rockets arrive',()=>{for(const n of [5,7]){const g=game(n);let seed=73;const rng=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed>>>31};let turns=0;while(g.phase==='playing'&&turns++<20000){const p=g.players[g.turn];if(g.step==='cast')perform(g,p.id,{type:'cast'},rng);else if(g.step==='move'){const moves=legalMoves(g);perform(g,p.id,{type:'move',rocket:moves[seed%moves.length]})}else perform(g,p.id,{type:'end'})}assert.equal(g.phase,'finished');assert.ok(g.players.find(p=>p.id===g.winner).rockets.every(x=>x===layout(n).path.length-1))}});
